import argparse
import os
import sqlite3
from typing import Any, Dict, Iterable, List, Sequence, Tuple

import psycopg


def _load_dotenv(path: str = ".env") -> Dict[str, str]:
    parsed: Dict[str, str] = {}
    if not os.path.exists(path):
        return parsed
    with open(path, "r", encoding="utf-8") as fh:
        for raw_line in fh:
            line = raw_line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            parsed[key.strip()] = value.strip()
    return parsed


def _env(dotenv: Dict[str, str], key: str, default: str = "") -> str:
    value = os.getenv(key)
    if value is not None:
        return value
    return dotenv.get(key, default)


def _pg_connect(dotenv: Dict[str, str]) -> Any:
    dsn = _env(dotenv, "AUTH_DB_DSN").strip()
    if dsn:
        return psycopg.connect(dsn)

    host = _env(dotenv, "AUTH_DB_HOST").strip()
    port = _env(dotenv, "AUTH_DB_PORT", "5432").strip()
    dbname = _env(dotenv, "AUTH_DB_NAME").strip()
    user = _env(dotenv, "AUTH_DB_USER").strip()
    password = _env(dotenv, "AUTH_DB_PASSWORD").strip()
    sslmode = _env(dotenv, "AUTH_DB_SSLMODE", "prefer").strip()

    missing = [
        name
        for name, value in (
            ("AUTH_DB_HOST", host),
            ("AUTH_DB_NAME", dbname),
            ("AUTH_DB_USER", user),
            ("AUTH_DB_PASSWORD", password),
        )
        if not value
    ]
    if missing:
        raise RuntimeError(
            "Missing PostgreSQL auth DB config. Set AUTH_DB_DSN or "
            + ", ".join(missing)
            + "."
        )

    return psycopg.connect(
        host=host,
        port=int(port),
        dbname=dbname,
        user=user,
        password=password,
        sslmode=sslmode,
    )


AUTH_SCHEMA_STATEMENTS = (
    """
    CREATE TABLE IF NOT EXISTS users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        email TEXT NOT NULL UNIQUE,
        organization TEXT NOT NULL DEFAULT '',
        use_case TEXT NOT NULL DEFAULT '',
        advocate_address TEXT NOT NULL DEFAULT '',
        advocate_mobile TEXT NOT NULL DEFAULT '',
        role TEXT NOT NULL CHECK (role IN ('admin', 'user')),
        status TEXT NOT NULL CHECK (status IN ('pending', 'granted', 'denied')),
        access_granted BOOLEAN NOT NULL DEFAULT FALSE,
        password_hash TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL
    )
    """,
    """
    CREATE UNIQUE INDEX IF NOT EXISTS uq_single_admin_role
    ON users(role) WHERE role = 'admin'
    """,
    """
    CREATE TABLE IF NOT EXISTS access_requests (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL,
        name TEXT NOT NULL,
        email TEXT NOT NULL,
        organization TEXT NOT NULL DEFAULT '',
        use_case TEXT NOT NULL DEFAULT '',
        status TEXT NOT NULL CHECK (status IN ('pending', 'granted', 'denied')),
        reviewed_by INTEGER,
        review_notes TEXT NOT NULL DEFAULT '',
        created_at TEXT NOT NULL,
        reviewed_at TEXT,
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
        FOREIGN KEY(reviewed_by) REFERENCES users(id) ON DELETE SET NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS password_setup_tokens (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL,
        token_hash TEXT NOT NULL UNIQUE,
        expires_at TEXT NOT NULL,
        used BOOLEAN NOT NULL DEFAULT FALSE,
        created_by_admin_id INTEGER,
        created_at TEXT NOT NULL,
        used_at TEXT,
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
        FOREIGN KEY(created_by_admin_id) REFERENCES users(id) ON DELETE SET NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS sessions (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL,
        token_hash TEXT NOT NULL UNIQUE,
        expires_at TEXT NOT NULL,
        revoked BOOLEAN NOT NULL DEFAULT FALSE,
        created_at TEXT NOT NULL,
        revoked_at TEXT,
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS chat_sessions (
        session_id TEXT PRIMARY KEY,
        user_id INTEGER NOT NULL,
        title TEXT NOT NULL,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        last_message_at TEXT NOT NULL,
        archived BOOLEAN NOT NULL DEFAULT FALSE,
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS chat_messages (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        session_id TEXT NOT NULL,
        user_id INTEGER NOT NULL,
        role TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
        content TEXT NOT NULL,
        created_at TEXT NOT NULL,
        FOREIGN KEY(session_id) REFERENCES chat_sessions(session_id) ON DELETE CASCADE,
        FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
    )
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_chat_sessions_user_last
    ON chat_sessions(user_id, last_message_at DESC)
    """,
    """
    CREATE INDEX IF NOT EXISTS idx_chat_messages_session_id
    ON chat_messages(session_id, id)
    """,
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS advocate_address TEXT NOT NULL DEFAULT ''",
    "ALTER TABLE users ADD COLUMN IF NOT EXISTS advocate_mobile TEXT NOT NULL DEFAULT ''",
)


def _sqlite_table_exists(conn: sqlite3.Connection, table_name: str) -> bool:
    row = conn.execute(
        "SELECT name FROM sqlite_master WHERE type = 'table' AND name = ?",
        (table_name,),
    ).fetchone()
    return row is not None


def _sqlite_rows(conn: sqlite3.Connection, table_name: str) -> List[sqlite3.Row]:
    if not _sqlite_table_exists(conn, table_name):
        return []
    return conn.execute(f"SELECT * FROM {table_name}").fetchall()


def _coerce_bool(value: Any) -> bool:
    return bool(value)


def _executemany(conn: Any, sql: str, rows: Sequence[Sequence[Any]]) -> None:
    if not rows:
        return
    with conn.cursor() as cur:
        cur.executemany(sql, rows)


def _reset_identity_sequences(conn: Any) -> None:
    for table in ("users", "access_requests", "password_setup_tokens", "sessions", "chat_messages"):
        conn.execute(
            f"""
            SELECT setval(
                pg_get_serial_sequence('{table}', 'id'),
                COALESCE((SELECT MAX(id) FROM {table}), 1),
                (SELECT COUNT(*) > 0 FROM {table})
            )
            """
        )


def migrate(sqlite_path: str, truncate_first: bool) -> None:
    if not os.path.exists(sqlite_path):
        raise FileNotFoundError(f"SQLite file not found: {sqlite_path}")

    dotenv = _load_dotenv()
    sqlite_conn = sqlite3.connect(sqlite_path)
    sqlite_conn.row_factory = sqlite3.Row

    with _pg_connect(dotenv) as pg_conn:
        for statement in AUTH_SCHEMA_STATEMENTS:
            pg_conn.execute(statement)

        if truncate_first:
            pg_conn.execute(
                """
                TRUNCATE TABLE
                    chat_messages,
                    chat_sessions,
                    sessions,
                    password_setup_tokens,
                    access_requests,
                    users
                RESTART IDENTITY CASCADE
                """
            )

        users = _sqlite_rows(sqlite_conn, "users")
        _executemany(
            pg_conn,
            """
            INSERT INTO users
            (id, name, email, organization, use_case, advocate_address, advocate_mobile, role, status, access_granted, password_hash, created_at, updated_at)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            """,
            [
                (
                    int(row["id"]),
                    row["name"],
                    row["email"],
                    row["organization"] or "",
                    row["use_case"] or "",
                    row["advocate_address"] if "advocate_address" in row.keys() else "",
                    row["advocate_mobile"] if "advocate_mobile" in row.keys() else "",
                    row["role"],
                    row["status"],
                    _coerce_bool(row["access_granted"]),
                    row["password_hash"],
                    row["created_at"],
                    row["updated_at"],
                )
                for row in users
            ],
        )

        access_requests = _sqlite_rows(sqlite_conn, "access_requests")
        _executemany(
            pg_conn,
            """
            INSERT INTO access_requests
            (id, user_id, name, email, organization, use_case, status, reviewed_by, review_notes, created_at, reviewed_at)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            """,
            [
                (
                    int(row["id"]),
                    int(row["user_id"]),
                    row["name"],
                    row["email"],
                    row["organization"] or "",
                    row["use_case"] or "",
                    row["status"],
                    int(row["reviewed_by"]) if row["reviewed_by"] is not None else None,
                    row["review_notes"] or "",
                    row["created_at"],
                    row["reviewed_at"],
                )
                for row in access_requests
            ],
        )

        password_setup_tokens = _sqlite_rows(sqlite_conn, "password_setup_tokens")
        _executemany(
            pg_conn,
            """
            INSERT INTO password_setup_tokens
            (id, user_id, token_hash, expires_at, used, created_by_admin_id, created_at, used_at)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
            """,
            [
                (
                    int(row["id"]),
                    int(row["user_id"]),
                    row["token_hash"],
                    row["expires_at"],
                    _coerce_bool(row["used"]),
                    int(row["created_by_admin_id"]) if row["created_by_admin_id"] is not None else None,
                    row["created_at"],
                    row["used_at"],
                )
                for row in password_setup_tokens
            ],
        )

        sessions = _sqlite_rows(sqlite_conn, "sessions")
        _executemany(
            pg_conn,
            """
            INSERT INTO sessions
            (id, user_id, token_hash, expires_at, revoked, created_at, revoked_at)
            VALUES (%s, %s, %s, %s, %s, %s, %s)
            """,
            [
                (
                    int(row["id"]),
                    int(row["user_id"]),
                    row["token_hash"],
                    row["expires_at"],
                    _coerce_bool(row["revoked"]),
                    row["created_at"],
                    row["revoked_at"],
                )
                for row in sessions
            ],
        )

        chat_sessions = _sqlite_rows(sqlite_conn, "chat_sessions")
        _executemany(
            pg_conn,
            """
            INSERT INTO chat_sessions
            (session_id, user_id, title, created_at, updated_at, last_message_at, archived)
            VALUES (%s, %s, %s, %s, %s, %s, %s)
            """,
            [
                (
                    row["session_id"],
                    int(row["user_id"]),
                    row["title"],
                    row["created_at"],
                    row["updated_at"],
                    row["last_message_at"],
                    _coerce_bool(row["archived"]),
                )
                for row in chat_sessions
            ],
        )

        chat_messages = _sqlite_rows(sqlite_conn, "chat_messages")
        _executemany(
            pg_conn,
            """
            INSERT INTO chat_messages
            (id, session_id, user_id, role, content, created_at)
            VALUES (%s, %s, %s, %s, %s, %s)
            """,
            [
                (
                    int(row["id"]),
                    row["session_id"],
                    int(row["user_id"]),
                    row["role"],
                    row["content"],
                    row["created_at"],
                )
                for row in chat_messages
            ],
        )

        _reset_identity_sequences(pg_conn)
        pg_conn.commit()

    sqlite_conn.close()

    print(f"Migrated users={len(users)}")
    print(f"Migrated access_requests={len(access_requests)}")
    print(f"Migrated password_setup_tokens={len(password_setup_tokens)}")
    print(f"Migrated sessions={len(sessions)}")
    print(f"Migrated chat_sessions={len(chat_sessions)}")
    print(f"Migrated chat_messages={len(chat_messages)}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Migrate auth_access.db from SQLite to PostgreSQL.")
    parser.add_argument(
        "--sqlite-path",
        default=os.getenv("SQLITE_AUTH_DB_PATH", "auth_access.db"),
        help="Path to the SQLite auth DB file.",
    )
    parser.add_argument(
        "--skip-truncate",
        action="store_true",
        help="Do not clear PostgreSQL auth tables before loading data.",
    )
    args = parser.parse_args()
    migrate(sqlite_path=args.sqlite_path, truncate_first=not args.skip_truncate)


if __name__ == "__main__":
    main()
