name: Deploy Dev to Test Server

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ['self-hosted', 'Linux', 'X64']

    steps:
    - name: Deploy dev branch on self-hosted test server
      run: |
        cd /home/lawllm/Test_Server/LAWLLM
        git fetch origin dev
        git checkout dev
        git pull origin dev
        source .venv/bin/activate
        pip install -r requirements.txt
        cd ui
        npm install
        sudo systemctl restart lawllm
        sudo systemctl restart lawllm-frontend
          
